apiVersion: v1
kind: Service
metadata:
  name: asteroids-svc
  namespace: games
  labels:
    app: asteroids
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: asteroids
