apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: border-runner-ingress
  namespace: games
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  ingressClassName: traefik
  rules:
    - host: border-runner.cdd.net.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: border-runner-svc
                port:
                  number: 80
