apiVersion: v1
kind: Service
metadata:
  name: border-runner-svc
  namespace: games
  labels:
    app: border-runner
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: border-runner
