apiVersion: v1
kind: Service
metadata:
  name: pong-evolution-svc
  namespace: games
  labels:
    app: pong-evolution
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: pong-evolution
