apiVersion: v1
kind: Service
metadata:
  name: pong-flask-svc
  namespace: games
  labels:
    app: pong-flask
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: pong-flask
